[build]
  functions = "functions"
  command = "npm run build"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200